package com.frank.ironbank;

public enum ExerciseType {
    BENCH_PRESS,
    SQUAT,
    DEADLIFT,
    OVERHEAD_PRESS,
    BARBELL_ROW,
    PULL_UP,
    DIP,
    PREACHER_CURL,
    TRICEP_EXTENSION,
    LEG_PRESS,
    LEG_CURL,
    LEG_EXTENSION,
    CALF_RAISE,
    CRUNCH,
    DUMBBELL_CURL,
    DUMBBELL_FLY,
    DUMBBELL_PRESS,
    DUMBBELL_ROW,
    PULL_DOWN,
    OVERHEAD_EXTENSION,
}