name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  greeting-job: # This is taken from the marketplace - actually throws a few deprecation warnings
    runs-on: ubuntu-latest
    steps:
      - name: Test Javascript Hello Action
        uses: adeloyedeji/github-actions-hello@v1.0
        with:
          who-to-greet: 'Frank'